"""Initial migration.

Revision ID: 8329a1fa4e14
Revises: 
Create Date: 2024-02-01 00:12:19.307017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8329a1fa4e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_index')
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('course_index', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('group', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('day', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'course_code', ['course_code'], ['course_code'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('html_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])
        batch_op.drop_column('remark')
        batch_op.drop_column('venue')
        batch_op.drop_column('time')
        batch_op.drop_column('day')
        batch_op.drop_column('group')
        batch_op.drop_column('type')
        batch_op.drop_column('course_index')
        batch_op.drop_column('user_id')

    op.create_table('course_index',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('index_number', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
